name: Naver Notice Checker

on:
  schedule:
    - cron: '0 22 * * *'   # 오전 7시 KST
    - cron: '0 10 * * *'   # 오후 7시 KST
  workflow_dispatch:  # 수동 실행 가능

jobs:
  check_notice:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 필요한 패키지 설치
        run: |
          pip install requests beautifulsoup4

      - name: 공지 확인 실행
        run: python check_notice.py
